// <auto-generated />
using System;
using EMAP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMAP.Infrastructure.Migrations
{
    [DbContext(typeof(EmapDbContext))]
    [Migration("20260311214154_AddFypStagesMilestonesEvaluations")]
    partial class AddFypStagesMilestonesEvaluations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMAP.Domain.Fyp.FypCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnnouncementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ProposalDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FypCalls");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypChapterAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("FypCallId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FypCallId");

                    b.ToTable("FypChapterAnnouncements");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypChapterSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterAnnouncementId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("MilestoneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterAnnouncementId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MilestoneId");

                    b.ToTable("FypChapterSubmissions");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluatorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<int>("MilestoneId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("FypEvaluations");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypEvaluationCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxMarks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationType", "DisplayOrder");

                    b.ToTable("FypEvaluationCriteria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            EvaluationType = 2,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Problem Understanding"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            EvaluationType = 2,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Progress and Methodology"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            EvaluationType = 2,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Documentation"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            EvaluationType = 2,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Presentation"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            EvaluationType = 3,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Implementation Progress"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 2,
                            EvaluationType = 3,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Documentation Quality"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 3,
                            EvaluationType = 3,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Presentation and Readiness"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            EvaluationType = 4,
                            IsActive = true,
                            MaxMarks = 20m,
                            Title = "Final Report"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 2,
                            EvaluationType = 4,
                            IsActive = true,
                            MaxMarks = 20m,
                            Title = "Implementation"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 3,
                            EvaluationType = 4,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Presentation"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 4,
                            EvaluationType = 4,
                            IsActive = true,
                            MaxMarks = 10m,
                            Title = "Viva / Question Answer"
                        });
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypEvaluationScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AwardedMarks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("FypEvaluationScores");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Stage", "Type", "ChapterNumber", "DisplayOrder");

                    b.ToTable("FypMilestones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterNumber = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 1,
                            Title = "FYP-1 Chapter 1",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            ChapterNumber = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 1,
                            Title = "FYP-1 Chapter 2",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            ChapterNumber = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 1,
                            Title = "FYP-1 Chapter 3",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 1,
                            Title = "FYP-1 Mid Evaluation",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 1,
                            Title = "FYP-1 Final Evaluation",
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            ChapterNumber = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 2,
                            Title = "FYP-2 Chapter 1",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            ChapterNumber = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 2,
                            Title = "FYP-2 Chapter 2",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            ChapterNumber = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 2,
                            Title = "FYP-2 Chapter 3",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 4,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 2,
                            Title = "FYP-2 Mid Evaluation",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 5,
                            IsActive = true,
                            IsOptional = true,
                            Stage = 2,
                            Title = "FYP-2 Pre-Final Evaluation",
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 6,
                            IsActive = true,
                            IsOptional = false,
                            Stage = 2,
                            Title = "FYP-2 Final Evaluation",
                            Type = 4
                        });
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FypCallId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FypCallId");

                    b.ToTable("FypProjects");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypSupervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentSlots")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FieldOfExpertise")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxSlots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("FypSupervisors");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.ProposalDefenseEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<int>("ProposalSubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProposalSubmissionId")
                        .IsUnique();

                    b.ToTable("ProposalDefenseEvaluations");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.ProposalDefenseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DefenseDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("DefenseTime")
                        .HasColumnType("time");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProposalSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProposalSubmissionId")
                        .IsUnique();

                    b.ToTable("ProposalDefenseSchedules");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.ProposalSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinalApproved")
                        .HasColumnType("bit");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("ProposalSubmissions");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int>("FypCallId")
                        .HasColumnType("int");

                    b.Property<string>("LeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member2Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member3Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("TentativeProjectTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("FypCallId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("EMAP.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypChapterAnnouncement", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.FypCall", "FypCall")
                        .WithMany()
                        .HasForeignKey("FypCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FypCall");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypChapterSubmission", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.FypChapterAnnouncement", "ChapterAnnouncement")
                        .WithMany()
                        .HasForeignKey("ChapterAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMAP.Domain.Fyp.StudentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMAP.Domain.Fyp.FypMilestone", "Milestone")
                        .WithMany("ChapterSubmissions")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChapterAnnouncement");

                    b.Navigation("Group");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypEvaluation", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.FypMilestone", "Milestone")
                        .WithMany("Evaluations")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMAP.Domain.Fyp.StudentGroup", "StudentGroup")
                        .WithMany("Evaluations")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypEvaluationScore", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.FypEvaluationCriterion", "Criterion")
                        .WithMany("Scores")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMAP.Domain.Fyp.FypEvaluation", "Evaluation")
                        .WithMany("Scores")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypProject", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.FypCall", "FypCall")
                        .WithMany("Projects")
                        .HasForeignKey("FypCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FypCall");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypSupervisor", b =>
                {
                    b.HasOne("EMAP.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMAP.Domain.Users.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.ProposalDefenseEvaluation", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.ProposalSubmission", "ProposalSubmission")
                        .WithOne("DefenseEvaluation")
                        .HasForeignKey("EMAP.Domain.Fyp.ProposalDefenseEvaluation", "ProposalSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposalSubmission");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.ProposalDefenseSchedule", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.ProposalSubmission", "ProposalSubmission")
                        .WithOne("DefenseSchedule")
                        .HasForeignKey("EMAP.Domain.Fyp.ProposalDefenseSchedule", "ProposalSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposalSubmission");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.ProposalSubmission", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.StudentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.StudentGroup", b =>
                {
                    b.HasOne("EMAP.Domain.Fyp.FypCall", "FypCall")
                        .WithMany()
                        .HasForeignKey("FypCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMAP.Domain.Fyp.FypProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("EMAP.Domain.Fyp.FypSupervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FypCall");

                    b.Navigation("Project");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EMAP.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EMAP.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMAP.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EMAP.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypCall", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypEvaluation", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypEvaluationCriterion", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.FypMilestone", b =>
                {
                    b.Navigation("ChapterSubmissions");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.ProposalSubmission", b =>
                {
                    b.Navigation("DefenseEvaluation");

                    b.Navigation("DefenseSchedule");
                });

            modelBuilder.Entity("EMAP.Domain.Fyp.StudentGroup", b =>
                {
                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
